package model.entidad;
// Generated 23-jun-2020 16:29:36 by Hibernate Tools 4.3.1



/**
 * TbMenu generated by hbm2java
 */
public class TbMenu  implements java.io.Serializable {


     private Integer codigoPlatillo;
     private String descripcionPlatillo;
     private String calorias;
     private int precio;
     private int descuento;
     private String nombrePlatillo;
     private int racion;
     private String imageurl;

    public TbMenu() {
    }

	
    public TbMenu(String descripcionPlatillo, String calorias, int precio, int descuento, String nombrePlatillo, int racion) {
        this.descripcionPlatillo = descripcionPlatillo;
        this.calorias = calorias;
        this.precio = precio;
        this.descuento = descuento;
        this.nombrePlatillo = nombrePlatillo;
        this.racion = racion;
    }
    public TbMenu(String descripcionPlatillo, String calorias, int precio, int descuento, String nombrePlatillo, int racion, String imageurl) {
       this.descripcionPlatillo = descripcionPlatillo;
       this.calorias = calorias;
       this.precio = precio;
       this.descuento = descuento;
       this.nombrePlatillo = nombrePlatillo;
       this.racion = racion;
       this.imageurl = imageurl;
    }
   
    public Integer getCodigoPlatillo() {
        return this.codigoPlatillo;
    }
    
    public void setCodigoPlatillo(Integer codigoPlatillo) {
        this.codigoPlatillo = codigoPlatillo;
    }
    public String getDescripcionPlatillo() {
        return this.descripcionPlatillo;
    }
    
    public void setDescripcionPlatillo(String descripcionPlatillo) {
        this.descripcionPlatillo = descripcionPlatillo;
    }
    public String getCalorias() {
        return this.calorias;
    }
    
    public void setCalorias(String calorias) {
        this.calorias = calorias;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public int getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }
    public String getNombrePlatillo() {
        return this.nombrePlatillo;
    }
    
    public void setNombrePlatillo(String nombrePlatillo) {
        this.nombrePlatillo = nombrePlatillo;
    }
    public int getRacion() {
        return this.racion;
    }
    
    public void setRacion(int racion) {
        this.racion = racion;
    }
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    @Override
    public String toString() {
        return "TbMenu{" + "codigoPlatillo=" + codigoPlatillo + ", descripcionPlatillo=" + descripcionPlatillo + ", calorias=" + calorias + ", precio=" + precio + ", descuento=" + descuento + ", nombrePlatillo=" + nombrePlatillo + ", racion=" + racion + ", imageurl=" + imageurl + '}';
    }




}


